production:
  clients:
    default:
     uri: mongodb://heroku_c2fr6909:8idon4b9l84bqcik0cm0oj126m@ds059694.mongolab.com:59694/heroku_c2fr6909
     hosts:
       - baptistebrassart.herokuapp.com:27017
     options:
       connect_timeout: 15

development:
  clients:
    default:
      database: bbrassart_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: bbrassart_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
